/**
 * Curated reaction/emoji catalog for context menu + sticker emoji tab.
 * Every entry was validated against local public/twemoji/72x72 PNGs
 * so TwemojiImg should not 404 (native glyph remains as last resort).
 */
export type ContextEmojiEntry = { emoji: string; keywords: string }

export const QUICK_CONTEXT_REACTIONS = [
  '👍',
  '❤️',
  '🔥',
  '😂',
  '😢',
] as const

export const ALL_CONTEXT_EMOJIS: ContextEmojiEntry[] = [
  { emoji: '😀', keywords: 'grin smile happy улыбка' },
  { emoji: '😃', keywords: 'smile happy радость' },
  { emoji: '😄', keywords: 'smile happy смех' },
  { emoji: '😁', keywords: 'grin smile улыбка радость' },
  { emoji: '😆', keywords: 'laughing смех' },
  { emoji: '😅', keywords: 'sweat smile смущение' },
  { emoji: '🤣', keywords: 'rofl смех ржу' },
  { emoji: '😂', keywords: 'joy tears смех слезы' },
  { emoji: '🙂', keywords: 'slight smile улыбка' },
  { emoji: '🙃', keywords: 'upside down ирония' },
  { emoji: '😉', keywords: 'wink подмигивание' },
  { emoji: '😊', keywords: 'blush улыбка' },
  { emoji: '😇', keywords: 'angel innocent ангел' },
  { emoji: '🥰', keywords: 'love smile hearts влюблен' },
  { emoji: '😍', keywords: 'heart eyes влюблен' },
  { emoji: '🤩', keywords: 'star eyes восторг' },
  { emoji: '😘', keywords: 'kiss wink поцелуй' },
  { emoji: '😗', keywords: 'kiss поцелуй' },
  { emoji: '😚', keywords: 'kiss closed eyes поцелуй' },
  { emoji: '😙', keywords: 'kiss smile поцелуй' },
  { emoji: '🥲', keywords: 'tear smile слеза улыбка' },
  { emoji: '😋', keywords: 'yum вкусно' },
  { emoji: '😛', keywords: 'tongue язык' },
  { emoji: '😜', keywords: 'wink tongue язык' },
  { emoji: '🤪', keywords: 'zany crazy безумный' },
  { emoji: '😝', keywords: 'squint tongue язык' },
  { emoji: '🤑', keywords: 'money money язык деньги' },
  { emoji: '🤗', keywords: 'hug обнимашки' },
  { emoji: '🤭', keywords: 'hand over mouth oops' },
  { emoji: '🤫', keywords: 'shush тихо' },
  { emoji: '🤔', keywords: 'thinking думаю хм' },
  { emoji: '🤐', keywords: 'zipper молчу' },
  { emoji: '🤨', keywords: 'raised eyebrow сомнение' },
  { emoji: '😐', keywords: 'neutral мех' },
  { emoji: '😑', keywords: 'expressionless' },
  { emoji: '😶', keywords: 'no mouth молчу' },
  { emoji: '🫥', keywords: 'dotted line' },
  { emoji: '😏', keywords: 'smirk ухмылка' },
  { emoji: '😒', keywords: 'unamused недоволен' },
  { emoji: '🙄', keywords: 'eye roll закатил глаза' },
  { emoji: '😬', keywords: 'grimace' },
  { emoji: '😮‍💨', keywords: 'exhale выдох' },
  { emoji: '🤥', keywords: 'lying нос' },
  { emoji: '😌', keywords: 'relieved спокойствие' },
  { emoji: '😔', keywords: 'pensive грусть' },
  { emoji: '😪', keywords: 'sleepy сон' },
  { emoji: '🤤', keywords: 'drooling' },
  { emoji: '😴', keywords: 'sleep сон' },
  { emoji: '😷', keywords: 'mask маска' },
  { emoji: '🤒', keywords: 'sick температура' },
  { emoji: '🤕', keywords: 'bandage травма' },
  { emoji: '🤢', keywords: 'nauseated тошнота' },
  { emoji: '🤮', keywords: 'vomit тошнота фу' },
  { emoji: '🤧', keywords: 'sneeze чих' },
  { emoji: '🥵', keywords: 'hot жарко' },
  { emoji: '🥶', keywords: 'cold холодно' },
  { emoji: '🥴', keywords: 'woozy пьяный' },
  { emoji: '😵', keywords: 'dizzy' },
  { emoji: '🤯', keywords: 'mind blown шок взрыв' },
  { emoji: '🤠', keywords: 'cowboy' },
  { emoji: '🥳', keywords: 'party праздник' },
  { emoji: '🥸', keywords: 'disguise' },
  { emoji: '😎', keywords: 'cool sunglasses крутой' },
  { emoji: '🤓', keywords: 'nerd очкарик' },
  { emoji: '🧐', keywords: 'monocle' },
  { emoji: '😕', keywords: 'confused' },
  { emoji: '😟', keywords: 'worried' },
  { emoji: '🙁', keywords: 'slight frown' },
  { emoji: '☹️', keywords: 'frown' },
  { emoji: '😮', keywords: 'open mouth' },
  { emoji: '😯', keywords: 'hushed' },
  { emoji: '😲', keywords: 'astonished' },
  { emoji: '😳', keywords: 'flushed смущение' },
  { emoji: '🥺', keywords: 'pleading умоляю' },
  { emoji: '😦', keywords: 'frowning' },
  { emoji: '😧', keywords: 'anguished' },
  { emoji: '😨', keywords: 'fearful страх' },
  { emoji: '😰', keywords: 'anxious sweat' },
  { emoji: '😥', keywords: 'sad relief' },
  { emoji: '😢', keywords: 'cry sad слезы грусть' },
  { emoji: '😭', keywords: 'sob плач реву' },
  { emoji: '😱', keywords: 'scream fear ужас крик' },
  { emoji: '😖', keywords: 'confounded' },
  { emoji: '😣', keywords: 'persevering' },
  { emoji: '😞', keywords: 'disappointed' },
  { emoji: '😓', keywords: 'downcast' },
  { emoji: '😩', keywords: 'weary' },
  { emoji: '😫', keywords: 'tired' },
  { emoji: '🥱', keywords: 'yawn зевота скука' },
  { emoji: '😤', keywords: 'triumph' },
  { emoji: '😡', keywords: 'rage angry злость' },
  { emoji: '😠', keywords: 'angry' },
  { emoji: '🤬', keywords: 'angry swear злость мат' },
  { emoji: '😈', keywords: 'devil smile демон' },
  { emoji: '👿', keywords: 'imp демон' },
  { emoji: '💀', keywords: 'skull череп' },
  { emoji: '☠️', keywords: 'skull crossbones' },
  { emoji: '💩', keywords: 'poop какашка' },
  { emoji: '🤡', keywords: 'clown клоун' },
  { emoji: '👹', keywords: 'ogre' },
  { emoji: '👺', keywords: 'goblin' },
  { emoji: '👻', keywords: 'ghost призрак' },
  { emoji: '👽', keywords: 'alien' },
  { emoji: '👾', keywords: 'alien invader инопланетянин' },
  { emoji: '🤖', keywords: 'robot' },
  { emoji: '😺', keywords: 'cat smile' },
  { emoji: '😸', keywords: 'cat grin' },
  { emoji: '😹', keywords: 'cat joy' },
  { emoji: '😻', keywords: 'cat heart eyes' },
  { emoji: '😼', keywords: 'cat smirk' },
  { emoji: '😽', keywords: 'cat kiss' },
  { emoji: '🙀', keywords: 'cat scream' },
  { emoji: '😿', keywords: 'cat cry' },
  { emoji: '😾', keywords: 'cat angry' },
  { emoji: '🙈', keywords: 'see no evil обезьяна' },
  { emoji: '🙉', keywords: 'hear no evil обезьяна' },
  { emoji: '🙊', keywords: 'speak no evil обезьяна' },
  { emoji: '💋', keywords: 'kiss поцелуй' },
  { emoji: '💌', keywords: 'love letter' },
  { emoji: '💘', keywords: 'cupid стрела сердце' },
  { emoji: '💝', keywords: 'heart ribbon' },
  { emoji: '💖', keywords: 'sparkling heart' },
  { emoji: '💗', keywords: 'growing heart' },
  { emoji: '💓', keywords: 'beating heart' },
  { emoji: '💞', keywords: 'revolving hearts' },
  { emoji: '💕', keywords: 'two hearts' },
  { emoji: '💟', keywords: 'heart decoration' },
  { emoji: '❣️', keywords: 'heart exclamation' },
  { emoji: '💔', keywords: 'broken heart разбитое сердце' },
  { emoji: '❤️‍🔥', keywords: 'heart on fire страсть' },
  { emoji: '❤️‍🩹', keywords: 'mending heart' },
  { emoji: '❤️', keywords: 'heart love сердце любовь' },
  { emoji: '🧡', keywords: 'orange heart' },
  { emoji: '💛', keywords: 'yellow heart' },
  { emoji: '💚', keywords: 'green heart' },
  { emoji: '💙', keywords: 'blue heart' },
  { emoji: '💜', keywords: 'purple heart' },
  { emoji: '🤎', keywords: 'brown heart' },
  { emoji: '🖤', keywords: 'black heart' },
  { emoji: '🤍', keywords: 'white heart' },
  { emoji: '💯', keywords: 'hundred сто процент' },
  { emoji: '💢', keywords: 'anger' },
  { emoji: '💥', keywords: 'boom' },
  { emoji: '💫', keywords: 'dizzy' },
  { emoji: '💦', keywords: 'sweat drops' },
  { emoji: '💨', keywords: 'dash' },
  { emoji: '🕳️', keywords: 'hole' },
  { emoji: '💣', keywords: 'bomb' },
  { emoji: '💬', keywords: 'speech' },
  { emoji: '👁️‍🗨️', keywords: 'eye in speech bubble' },
  { emoji: '🗨️', keywords: 'left speech' },
  { emoji: '🗯️', keywords: 'right anger' },
  { emoji: '💭', keywords: 'thought' },
  { emoji: '💤', keywords: 'zzz' },
  { emoji: '👋', keywords: 'wave привет' },
  { emoji: '🤚', keywords: 'raised back hand' },
  { emoji: '🖐️', keywords: 'hand splayed' },
  { emoji: '✋', keywords: 'hand stop' },
  { emoji: '🖖', keywords: 'vulcan' },
  { emoji: '🫱', keywords: 'rightwards hand' },
  { emoji: '🫲', keywords: 'leftwards hand' },
  { emoji: '🫳', keywords: 'palm down' },
  { emoji: '🫴', keywords: 'palm up' },
  { emoji: '👌', keywords: 'ok okay окей' },
  { emoji: '🤌', keywords: 'pinched fingers' },
  { emoji: '🤏', keywords: 'pinching hand' },
  { emoji: '✌️', keywords: 'victory' },
  { emoji: '🤞', keywords: 'crossed fingers' },
  { emoji: '🫰', keywords: 'hand with index and thumb' },
  { emoji: '🤟', keywords: 'love you' },
  { emoji: '🤘', keywords: 'rock on' },
  { emoji: '🤙', keywords: 'call me' },
  { emoji: '👈', keywords: 'point left' },
  { emoji: '👉', keywords: 'point right' },
  { emoji: '👆', keywords: 'point up' },
  { emoji: '🖕', keywords: 'middle finger фак' },
  { emoji: '👇', keywords: 'point down' },
  { emoji: '☝️', keywords: 'index up' },
  { emoji: '🫵', keywords: 'point at viewer' },
  { emoji: '👍', keywords: 'like thumb up лайк плюс' },
  { emoji: '👎', keywords: 'dislike thumb down дизлайк минус' },
  { emoji: '✊', keywords: 'fist' },
  { emoji: '👊', keywords: 'punch' },
  { emoji: '🤛', keywords: 'left fist' },
  { emoji: '🤜', keywords: 'right fist' },
  { emoji: '👏', keywords: 'clap applause аплодисменты' },
  { emoji: '🙌', keywords: 'raised hands' },
  { emoji: '🫶', keywords: 'heart hands' },
  { emoji: '👐', keywords: 'open hands' },
  { emoji: '🤲', keywords: 'palms up' },
  { emoji: '🤝', keywords: 'handshake рукопожатие' },
  { emoji: '🙏', keywords: 'pray thanks пожалуйста спасибо' },
  { emoji: '✍️', keywords: 'writing пишу' },
  { emoji: '💅', keywords: 'nails маникюр' },
  { emoji: '🤳', keywords: 'selfie' },
  { emoji: '💪', keywords: 'muscle сила' },
  { emoji: '🦾', keywords: 'mechanical arm' },
  { emoji: '🦿', keywords: 'mechanical leg' },
  { emoji: '🦵', keywords: 'leg' },
  { emoji: '🦶', keywords: 'foot' },
  { emoji: '👂', keywords: 'ear' },
  { emoji: '🦻', keywords: 'ear hearing' },
  { emoji: '👃', keywords: 'nose' },
  { emoji: '🧠', keywords: 'brain' },
  { emoji: '🫀', keywords: 'heart organ' },
  { emoji: '🫁', keywords: 'lungs' },
  { emoji: '🦷', keywords: 'tooth' },
  { emoji: '🦴', keywords: 'bone' },
  { emoji: '👀', keywords: 'eyes глаза смотрю' },
  { emoji: '👁️', keywords: 'eye' },
  { emoji: '👅', keywords: 'tongue' },
  { emoji: '👄', keywords: 'mouth' },
  { emoji: '🫦', keywords: 'biting lip' },
  { emoji: '👶', keywords: 'baby' },
  { emoji: '🧒', keywords: 'child' },
  { emoji: '👦', keywords: 'boy' },
  { emoji: '👧', keywords: 'girl' },
  { emoji: '🧑', keywords: 'person' },
  { emoji: '👱', keywords: 'blond' },
  { emoji: '👨', keywords: 'man' },
  { emoji: '🧔', keywords: 'beard' },
  { emoji: '👩', keywords: 'woman' },
  { emoji: '🧓', keywords: 'older' },
  { emoji: '👴', keywords: 'old man' },
  { emoji: '👵', keywords: 'old woman' },
  { emoji: '🙍', keywords: 'frowning person' },
  { emoji: '🙎', keywords: 'pouting' },
  { emoji: '🙅', keywords: 'no gesture' },
  { emoji: '🙆', keywords: 'ok gesture' },
  { emoji: '💁', keywords: 'tipping hand' },
  { emoji: '🙋', keywords: 'raising hand' },
  { emoji: '🧏', keywords: 'deaf' },
  { emoji: '🙇', keywords: 'bow' },
  { emoji: '🤦', keywords: 'facepalm' },
  { emoji: '🤷', keywords: 'shrug хз незнаю' },
  { emoji: '🤷‍♂️', keywords: 'shrug мужчина хз' },
  { emoji: '🤷‍♀️', keywords: 'shrug женщина хз' },
  { emoji: '👨‍⚕️', keywords: 'man health' },
  { emoji: '👩‍⚕️', keywords: 'woman health' },
  { emoji: '👨‍🎓', keywords: 'man student' },
  { emoji: '👩‍🎓', keywords: 'woman student' },
  { emoji: '👨‍💻', keywords: 'coder programmer разработчик' },
  { emoji: '👩‍💻', keywords: 'woman coder' },
  { emoji: '👨‍🚀', keywords: 'man astronaut' },
  { emoji: '👩‍🚀', keywords: 'woman astronaut' },
  { emoji: '👮', keywords: 'police' },
  { emoji: '🕵️', keywords: 'detective' },
  { emoji: '💂', keywords: 'guard' },
  { emoji: '🥷', keywords: 'ninja' },
  { emoji: '👷', keywords: 'construction' },
  { emoji: '🤴', keywords: 'prince' },
  { emoji: '👸', keywords: 'princess' },
  { emoji: '👳', keywords: 'turban' },
  { emoji: '👲', keywords: 'gua pi mao' },
  { emoji: '🧕', keywords: 'headscarf' },
  { emoji: '🤵', keywords: 'tuxedo' },
  { emoji: '👰', keywords: 'bride' },
  { emoji: '🤰', keywords: 'pregnant' },
  { emoji: '🤱', keywords: 'breast feeding' },
  { emoji: '👼', keywords: 'baby angel' },
  { emoji: '🎅', keywords: 'santa дед мороз' },
  { emoji: '🤶', keywords: 'mrs claus' },
  { emoji: '🦸', keywords: 'superhero' },
  { emoji: '🦹', keywords: 'supervillain' },
  { emoji: '🧙', keywords: 'mage' },
  { emoji: '🧚', keywords: 'fairy' },
  { emoji: '🧛', keywords: 'vampire' },
  { emoji: '🧜', keywords: 'merperson' },
  { emoji: '🧝', keywords: 'elf' },
  { emoji: '🧞', keywords: 'genie' },
  { emoji: '🧟', keywords: 'zombie' },
  { emoji: '💆', keywords: 'massage' },
  { emoji: '💇', keywords: 'haircut' },
  { emoji: '🚶', keywords: 'walking' },
  { emoji: '🧍', keywords: 'standing' },
  { emoji: '🧎', keywords: 'kneeling' },
  { emoji: '🏃', keywords: 'running' },
  { emoji: '💃', keywords: 'dancer' },
  { emoji: '🕺', keywords: 'man dancing' },
  { emoji: '🕴️', keywords: 'levitate' },
  { emoji: '👯', keywords: 'dancers' },
  { emoji: '🧖', keywords: 'sauna' },
  { emoji: '🧗', keywords: 'climbing' },
  { emoji: '🤺', keywords: 'fencing' },
  { emoji: '🏇', keywords: 'horse racing' },
  { emoji: '⛷️', keywords: 'skier' },
  { emoji: '🏂', keywords: 'snowboarder' },
  { emoji: '🏌️', keywords: 'golfing' },
  { emoji: '🏄', keywords: 'surfing' },
  { emoji: '🚣', keywords: 'rowing' },
  { emoji: '🏊', keywords: 'swimming' },
  { emoji: '⛹️', keywords: 'bouncing ball' },
  { emoji: '🏋️', keywords: 'weightlifting' },
  { emoji: '🚴', keywords: 'biking' },
  { emoji: '🚵', keywords: 'mountain bike' },
  { emoji: '🤸', keywords: 'cartwheel' },
  { emoji: '🤼', keywords: 'wrestling' },
  { emoji: '🤽', keywords: 'water polo' },
  { emoji: '🤾', keywords: 'handball' },
  { emoji: '🤹', keywords: 'juggling' },
  { emoji: '🧘', keywords: 'lotus' },
  { emoji: '🛀', keywords: 'bath' },
  { emoji: '🛌', keywords: 'sleeping bed' },
  { emoji: '🧑‍🤝‍🧑', keywords: 'people holding hands' },
  { emoji: '👭', keywords: 'women holding hands' },
  { emoji: '👫', keywords: 'woman man holding hands' },
  { emoji: '👬', keywords: 'men holding hands' },
  { emoji: '💏', keywords: 'kiss couple' },
  { emoji: '💑', keywords: 'couple heart' },
  { emoji: '👪', keywords: 'family' },
  { emoji: '🗣️', keywords: 'speaking head' },
  { emoji: '👤', keywords: 'bust' },
  { emoji: '👥', keywords: 'busts' },
  { emoji: '🫂', keywords: 'people hugging' },
  { emoji: '👣', keywords: 'footprints' },
  { emoji: '🐵', keywords: 'monkey face' },
  { emoji: '🐒', keywords: 'monkey' },
  { emoji: '🦍', keywords: 'gorilla' },
  { emoji: '🦧', keywords: 'orangutan' },
  { emoji: '🐶', keywords: 'dog face' },
  { emoji: '🐕', keywords: 'dog' },
  { emoji: '🦮', keywords: 'guide dog' },
  { emoji: '🐩', keywords: 'poodle' },
  { emoji: '🐺', keywords: 'wolf' },
  { emoji: '🦊', keywords: 'fox' },
  { emoji: '🦝', keywords: 'raccoon' },
  { emoji: '🐱', keywords: 'cat face' },
  { emoji: '🐈', keywords: 'cat' },
  { emoji: '🦁', keywords: 'lion' },
  { emoji: '🐯', keywords: 'tiger face' },
  { emoji: '🐅', keywords: 'tiger' },
  { emoji: '🐆', keywords: 'leopard' },
  { emoji: '🐴', keywords: 'horse face' },
  { emoji: '🐎', keywords: 'horse' },
  { emoji: '🦄', keywords: 'unicorn единорог' },
  { emoji: '🦓', keywords: 'zebra' },
  { emoji: '🦌', keywords: 'deer' },
  { emoji: '🦬', keywords: 'bison' },
  { emoji: '🐮', keywords: 'cow face' },
  { emoji: '🐂', keywords: 'ox' },
  { emoji: '🐃', keywords: 'water buffalo' },
  { emoji: '🐄', keywords: 'cow' },
  { emoji: '🐷', keywords: 'pig face' },
  { emoji: '🐖', keywords: 'pig' },
  { emoji: '🐗', keywords: 'boar' },
  { emoji: '🐽', keywords: 'pig nose' },
  { emoji: '🐏', keywords: 'ram' },
  { emoji: '🐑', keywords: 'ewe' },
  { emoji: '🐐', keywords: 'goat' },
  { emoji: '🐪', keywords: 'camel' },
  { emoji: '🐫', keywords: 'two hump camel' },
  { emoji: '🦙', keywords: 'llama' },
  { emoji: '🦒', keywords: 'giraffe' },
  { emoji: '🐘', keywords: 'elephant' },
  { emoji: '🦣', keywords: 'mammoth' },
  { emoji: '🦏', keywords: 'rhino' },
  { emoji: '🦛', keywords: 'hippo' },
  { emoji: '🐭', keywords: 'mouse face' },
  { emoji: '🐁', keywords: 'mouse' },
  { emoji: '🐀', keywords: 'rat' },
  { emoji: '🐹', keywords: 'hamster' },
  { emoji: '🐰', keywords: 'rabbit face' },
  { emoji: '🐇', keywords: 'rabbit' },
  { emoji: '🐿️', keywords: 'chipmunk' },
  { emoji: '🦫', keywords: 'beaver' },
  { emoji: '🦔', keywords: 'hedgehog' },
  { emoji: '🦇', keywords: 'bat' },
  { emoji: '🐻', keywords: 'bear' },
  { emoji: '🐨', keywords: 'koala' },
  { emoji: '🐼', keywords: 'panda' },
  { emoji: '🦥', keywords: 'sloth' },
  { emoji: '🦦', keywords: 'otter' },
  { emoji: '🦨', keywords: 'skunk' },
  { emoji: '🦘', keywords: 'kangaroo' },
  { emoji: '🦡', keywords: 'badger' },
  { emoji: '🐾', keywords: 'paw' },
  { emoji: '🦃', keywords: 'turkey' },
  { emoji: '🐔', keywords: 'chicken' },
  { emoji: '🐓', keywords: 'rooster' },
  { emoji: '🐣', keywords: 'hatching chick' },
  { emoji: '🐤', keywords: 'baby chick' },
  { emoji: '🐥', keywords: 'front chick' },
  { emoji: '🐦', keywords: 'bird' },
  { emoji: '🐧', keywords: 'penguin' },
  { emoji: '🕊️', keywords: 'dove peace голубь мир' },
  { emoji: '🦅', keywords: 'eagle' },
  { emoji: '🦆', keywords: 'duck' },
  { emoji: '🦢', keywords: 'swan' },
  { emoji: '🦉', keywords: 'owl' },
  { emoji: '🦤', keywords: 'dodo' },
  { emoji: '🪶', keywords: 'feather' },
  { emoji: '🦩', keywords: 'flamingo' },
  { emoji: '🦚', keywords: 'peacock' },
  { emoji: '🦜', keywords: 'parrot' },
  { emoji: '🐸', keywords: 'frog' },
  { emoji: '🐊', keywords: 'crocodile' },
  { emoji: '🐢', keywords: 'turtle' },
  { emoji: '🦎', keywords: 'lizard' },
  { emoji: '🐍', keywords: 'snake' },
  { emoji: '🐲', keywords: 'dragon face' },
  { emoji: '🐉', keywords: 'dragon' },
  { emoji: '🦕', keywords: 'sauropod' },
  { emoji: '🦖', keywords: 't-rex' },
  { emoji: '🐳', keywords: 'whale кит' },
  { emoji: '🐋', keywords: 'whale' },
  { emoji: '🐬', keywords: 'dolphin' },
  { emoji: '🦭', keywords: 'seal' },
  { emoji: '🐟', keywords: 'fish' },
  { emoji: '🐠', keywords: 'tropical fish' },
  { emoji: '🐡', keywords: 'blowfish' },
  { emoji: '🦈', keywords: 'shark' },
  { emoji: '🐙', keywords: 'octopus' },
  { emoji: '🐚', keywords: 'shell' },
  { emoji: '🪸', keywords: 'coral' },
  { emoji: '🐌', keywords: 'snail' },
  { emoji: '🦋', keywords: 'butterfly' },
  { emoji: '🐛', keywords: 'bug' },
  { emoji: '🐜', keywords: 'ant' },
  { emoji: '🐝', keywords: 'bee' },
  { emoji: '🪲', keywords: 'beetle' },
  { emoji: '🐞', keywords: 'lady beetle' },
  { emoji: '🦗', keywords: 'cricket' },
  { emoji: '🪳', keywords: 'cockroach' },
  { emoji: '🕷️', keywords: 'spider' },
  { emoji: '🕸️', keywords: 'web' },
  { emoji: '🦂', keywords: 'scorpion' },
  { emoji: '🦟', keywords: 'mosquito' },
  { emoji: '🪰', keywords: 'fly' },
  { emoji: '🪱', keywords: 'worm' },
  { emoji: '🦠', keywords: 'microbe' },
  { emoji: '💐', keywords: 'bouquet' },
  { emoji: '🌸', keywords: 'cherry blossom' },
  { emoji: '💮', keywords: 'white flower' },
  { emoji: '🏵️', keywords: 'rosette' },
  { emoji: '🌹', keywords: 'rose' },
  { emoji: '🥀', keywords: 'wilted' },
  { emoji: '🌺', keywords: 'hibiscus' },
  { emoji: '🌻', keywords: 'sunflower' },
  { emoji: '🌼', keywords: 'blossom' },
  { emoji: '🌷', keywords: 'tulip' },
  { emoji: '🌱', keywords: 'seedling' },
  { emoji: '🪴', keywords: 'potted plant' },
  { emoji: '🌲', keywords: 'evergreen' },
  { emoji: '🌳', keywords: 'deciduous' },
  { emoji: '🌴', keywords: 'palm' },
  { emoji: '🌵', keywords: 'cactus' },
  { emoji: '🌾', keywords: 'sheaf' },
  { emoji: '🌿', keywords: 'herb' },
  { emoji: '☘️', keywords: 'shamrock' },
  { emoji: '🍀', keywords: 'clover' },
  { emoji: '🍁', keywords: 'maple' },
  { emoji: '🍂', keywords: 'fallen leaf' },
  { emoji: '🍃', keywords: 'leaf flutter' },
  { emoji: '🪹', keywords: 'empty nest' },
  { emoji: '🪺', keywords: 'nest eggs' },
  { emoji: '🍇', keywords: 'grapes' },
  { emoji: '🍈', keywords: 'melon' },
  { emoji: '🍉', keywords: 'watermelon' },
  { emoji: '🍊', keywords: 'tangerine' },
  { emoji: '🍋', keywords: 'lemon' },
  { emoji: '🍌', keywords: 'banana банан' },
  { emoji: '🍍', keywords: 'pineapple' },
  { emoji: '🥭', keywords: 'mango' },
  { emoji: '🍎', keywords: 'red apple' },
  { emoji: '🍏', keywords: 'green apple' },
  { emoji: '🍐', keywords: 'pear' },
  { emoji: '🍑', keywords: 'peach' },
  { emoji: '🍒', keywords: 'cherries' },
  { emoji: '🍓', keywords: 'strawberry клубника' },
  { emoji: '🫐', keywords: 'blueberries' },
  { emoji: '🥝', keywords: 'kiwi' },
  { emoji: '🍅', keywords: 'tomato' },
  { emoji: '🫒', keywords: 'olive' },
  { emoji: '🥥', keywords: 'coconut' },
  { emoji: '🥑', keywords: 'avocado' },
  { emoji: '🍆', keywords: 'eggplant' },
  { emoji: '🥔', keywords: 'potato' },
  { emoji: '🥕', keywords: 'carrot' },
  { emoji: '🌽', keywords: 'corn' },
  { emoji: '🌶️', keywords: 'pepper' },
  { emoji: '🫑', keywords: 'bell pepper' },
  { emoji: '🥒', keywords: 'cucumber' },
  { emoji: '🥬', keywords: 'leafy green' },
  { emoji: '🥦', keywords: 'broccoli' },
  { emoji: '🧄', keywords: 'garlic' },
  { emoji: '🧅', keywords: 'onion' },
  { emoji: '🍄', keywords: 'mushroom' },
  { emoji: '🥜', keywords: 'peanuts' },
  { emoji: '🌰', keywords: 'chestnut' },
  { emoji: '🍞', keywords: 'bread' },
  { emoji: '🥐', keywords: 'croissant' },
  { emoji: '🥖', keywords: 'baguette' },
  { emoji: '🫓', keywords: 'flatbread' },
  { emoji: '🥨', keywords: 'pretzel' },
  { emoji: '🥯', keywords: 'bagel' },
  { emoji: '🥞', keywords: 'pancakes' },
  { emoji: '🧇', keywords: 'waffle' },
  { emoji: '🧀', keywords: 'cheese' },
  { emoji: '🍖', keywords: 'meat' },
  { emoji: '🍗', keywords: 'poultry' },
  { emoji: '🥩', keywords: 'cut of meat' },
  { emoji: '🥓', keywords: 'bacon' },
  { emoji: '🍔', keywords: 'hamburger' },
  { emoji: '🍟', keywords: 'fries' },
  { emoji: '🍕', keywords: 'pizza' },
  { emoji: '🌭', keywords: 'hotdog хотдог' },
  { emoji: '🥪', keywords: 'sandwich' },
  { emoji: '🌮', keywords: 'taco' },
  { emoji: '🌯', keywords: 'burrito' },
  { emoji: '🫔', keywords: 'tamale' },
  { emoji: '🥙', keywords: 'stuffed flatbread' },
  { emoji: '🧆', keywords: 'falafel' },
  { emoji: '🥚', keywords: 'egg' },
  { emoji: '🍳', keywords: 'cooking' },
  { emoji: '🥘', keywords: 'shallow pan' },
  { emoji: '🍲', keywords: 'stew' },
  { emoji: '🫕', keywords: 'fondue' },
  { emoji: '🥣', keywords: 'bowl spoon' },
  { emoji: '🥗', keywords: 'salad' },
  { emoji: '🍿', keywords: 'popcorn' },
  { emoji: '🧈', keywords: 'butter' },
  { emoji: '🧂', keywords: 'salt' },
  { emoji: '🥫', keywords: 'canned food' },
  { emoji: '🍱', keywords: 'bento' },
  { emoji: '🍘', keywords: 'rice cracker' },
  { emoji: '🍙', keywords: 'rice ball' },
  { emoji: '🍚', keywords: 'cooked rice' },
  { emoji: '🍛', keywords: 'curry' },
  { emoji: '🍜', keywords: 'ramen' },
  { emoji: '🍝', keywords: 'spaghetti' },
  { emoji: '🍠', keywords: 'sweet potato' },
  { emoji: '🍢', keywords: 'oden' },
  { emoji: '🍣', keywords: 'sushi' },
  { emoji: '🍤', keywords: 'fried shrimp' },
  { emoji: '🍥', keywords: 'fish cake' },
  { emoji: '🥮', keywords: 'moon cake' },
  { emoji: '🍡', keywords: 'dango' },
  { emoji: '🥟', keywords: 'dumpling' },
  { emoji: '🥠', keywords: 'fortune cookie' },
  { emoji: '🥡', keywords: 'takeout' },
  { emoji: '🦀', keywords: 'crab' },
  { emoji: '🦞', keywords: 'lobster' },
  { emoji: '🦐', keywords: 'shrimp' },
  { emoji: '🦑', keywords: 'squid' },
  { emoji: '🦪', keywords: 'oyster' },
  { emoji: '🍦', keywords: 'soft ice cream' },
  { emoji: '🍧', keywords: 'shaved ice' },
  { emoji: '🍨', keywords: 'ice cream' },
  { emoji: '🍩', keywords: 'doughnut' },
  { emoji: '🍪', keywords: 'cookie' },
  { emoji: '🎂', keywords: 'birthday' },
  { emoji: '🍰', keywords: 'shortcake' },
  { emoji: '🧁', keywords: 'cupcake' },
  { emoji: '🥧', keywords: 'pie' },
  { emoji: '🍫', keywords: 'chocolate' },
  { emoji: '🍬', keywords: 'candy' },
  { emoji: '🍭', keywords: 'lollipop' },
  { emoji: '🍮', keywords: 'custard' },
  { emoji: '🍯', keywords: 'honey' },
  { emoji: '🍼', keywords: 'baby bottle' },
  { emoji: '🥛', keywords: 'milk' },
  { emoji: '☕', keywords: 'coffee' },
  { emoji: '🫖', keywords: 'teapot' },
  { emoji: '🍵', keywords: 'tea' },
  { emoji: '🍶', keywords: 'sake' },
  { emoji: '🍾', keywords: 'champagne шампанское' },
  { emoji: '🍷', keywords: 'wine' },
  { emoji: '🍸', keywords: 'cocktail' },
  { emoji: '🍹', keywords: 'tropical drink' },
  { emoji: '🍺', keywords: 'beer' },
  { emoji: '🍻', keywords: 'cheers' },
  { emoji: '🥂', keywords: 'clinking glasses' },
  { emoji: '🥃', keywords: 'tumbler' },
  { emoji: '🫗', keywords: 'pour' },
  { emoji: '🥤', keywords: 'cup straw' },
  { emoji: '🧋', keywords: 'bubble tea' },
  { emoji: '🧃', keywords: 'beverage box' },
  { emoji: '🧉', keywords: 'mate' },
  { emoji: '🧊', keywords: 'ice' },
  { emoji: '🥢', keywords: 'chopsticks' },
  { emoji: '🍽️', keywords: 'fork knife plate' },
  { emoji: '🍴', keywords: 'fork knife' },
  { emoji: '🥄', keywords: 'spoon' },
  { emoji: '🔪', keywords: 'knife' },
  { emoji: '🫙', keywords: 'jar' },
  { emoji: '🏺', keywords: 'amphora' },
  { emoji: '🌍', keywords: 'globe europe' },
  { emoji: '🌎', keywords: 'globe americas' },
  { emoji: '🌏', keywords: 'globe asia' },
  { emoji: '🌐', keywords: 'globe meridians' },
  { emoji: '🗺️', keywords: 'world map' },
  { emoji: '🗾', keywords: 'japan map' },
  { emoji: '🧭', keywords: 'compass' },
  { emoji: '🏔️', keywords: 'snow mountain' },
  { emoji: '⛰️', keywords: 'mountain' },
  { emoji: '🌋', keywords: 'volcano' },
  { emoji: '🗻', keywords: 'fuji' },
  { emoji: '🏕️', keywords: 'camping' },
  { emoji: '🏖️', keywords: 'beach' },
  { emoji: '🏜️', keywords: 'desert' },
  { emoji: '🏝️', keywords: 'island' },
  { emoji: '🏞️', keywords: 'park' },
  { emoji: '🏟️', keywords: 'stadium' },
  { emoji: '🏛️', keywords: 'classical building' },
  { emoji: '🏗️', keywords: 'construction' },
  { emoji: '🧱', keywords: 'brick' },
  { emoji: '🪨', keywords: 'rock' },
  { emoji: '🪵', keywords: 'wood' },
  { emoji: '🛖', keywords: 'hut' },
  { emoji: '🏘️', keywords: 'houses' },
  { emoji: '🏚️', keywords: 'derelict' },
  { emoji: '🏠', keywords: 'house' },
  { emoji: '🏡', keywords: 'house garden' },
  { emoji: '🏢', keywords: 'office' },
  { emoji: '🏣', keywords: 'japanese post' },
  { emoji: '🏤', keywords: 'post office' },
  { emoji: '🏥', keywords: 'hospital' },
  { emoji: '🏦', keywords: 'bank' },
  { emoji: '🏨', keywords: 'hotel' },
  { emoji: '🏩', keywords: 'love hotel' },
  { emoji: '🏪', keywords: 'convenience' },
  { emoji: '🏫', keywords: 'school' },
  { emoji: '🏬', keywords: 'department' },
  { emoji: '🏭', keywords: 'factory' },
  { emoji: '🏯', keywords: 'castle' },
  { emoji: '🏰', keywords: 'european castle' },
  { emoji: '💒', keywords: 'wedding' },
  { emoji: '🗼', keywords: 'tokyo tower' },
  { emoji: '🗽', keywords: 'statue liberty' },
  { emoji: '⛪', keywords: 'church' },
  { emoji: '🕌', keywords: 'mosque' },
  { emoji: '🛕', keywords: 'hindu temple' },
  { emoji: '🕍', keywords: 'synagogue' },
  { emoji: '⛩️', keywords: 'shinto' },
  { emoji: '🕋', keywords: 'kaaba' },
  { emoji: '⛲', keywords: 'fountain' },
  { emoji: '⛺', keywords: 'tent' },
  { emoji: '🌁', keywords: 'foggy' },
  { emoji: '🌃', keywords: 'night' },
  { emoji: '🏙️', keywords: 'cityscape' },
  { emoji: '🌄', keywords: 'sunrise mountain' },
  { emoji: '🌅', keywords: 'sunrise' },
  { emoji: '🌆', keywords: 'city dusk' },
  { emoji: '🌇', keywords: 'sunset' },
  { emoji: '🌉', keywords: 'bridge night' },
  { emoji: '♨️', keywords: 'hotsprings' },
  { emoji: '🎠', keywords: 'carousel' },
  { emoji: '🎡', keywords: 'ferris' },
  { emoji: '🎢', keywords: 'roller coaster' },
  { emoji: '💈', keywords: 'barber' },
  { emoji: '🎪', keywords: 'circus' },
  { emoji: '🚂', keywords: 'locomotive' },
  { emoji: '🚃', keywords: 'railway car' },
  { emoji: '🚄', keywords: 'bullet train' },
  { emoji: '🚅', keywords: 'bullet train2' },
  { emoji: '🚆', keywords: 'train' },
  { emoji: '🚇', keywords: 'metro' },
  { emoji: '🚈', keywords: 'light rail' },
  { emoji: '🚉', keywords: 'station' },
  { emoji: '🚊', keywords: 'tram' },
  { emoji: '🚝', keywords: 'monorail' },
  { emoji: '🚞', keywords: 'mountain railway' },
  { emoji: '🚋', keywords: 'tram car' },
  { emoji: '🚌', keywords: 'bus' },
  { emoji: '🚍', keywords: 'oncoming bus' },
  { emoji: '🚎', keywords: 'trolleybus' },
  { emoji: '🚐', keywords: 'minibus' },
  { emoji: '🚑', keywords: 'ambulance' },
  { emoji: '🚒', keywords: 'fire engine' },
  { emoji: '🚓', keywords: 'police car' },
  { emoji: '🚔', keywords: 'oncoming police' },
  { emoji: '🚕', keywords: 'taxi' },
  { emoji: '🚖', keywords: 'oncoming taxi' },
  { emoji: '🚗', keywords: 'car' },
  { emoji: '🚘', keywords: 'oncoming car' },
  { emoji: '🚙', keywords: 'suv' },
  { emoji: '🛻', keywords: 'pickup' },
  { emoji: '🚚', keywords: 'delivery truck' },
  { emoji: '🚛', keywords: 'articulated' },
  { emoji: '🚜', keywords: 'tractor' },
  { emoji: '🏎️', keywords: 'racing car' },
  { emoji: '🏍️', keywords: 'motorcycle' },
  { emoji: '🛵', keywords: 'motor scooter' },
  { emoji: '🦽', keywords: 'manual wheelchair' },
  { emoji: '🦼', keywords: 'motorized wheelchair' },
  { emoji: '🛺', keywords: 'auto rickshaw' },
  { emoji: '🚲', keywords: 'bicycle' },
  { emoji: '🛴', keywords: 'kick scooter' },
  { emoji: '🛹', keywords: 'skateboard' },
  { emoji: '🛼', keywords: 'roller skate' },
  { emoji: '🚏', keywords: 'bus stop' },
  { emoji: '🛣️', keywords: 'motorway' },
  { emoji: '🛤️', keywords: 'railway track' },
  { emoji: '🛢️', keywords: 'oil drum' },
  { emoji: '⛽', keywords: 'fuel' },
  { emoji: '🚨', keywords: 'revolving light' },
  { emoji: '🚥', keywords: 'horizontal traffic' },
  { emoji: '🚦', keywords: 'vertical traffic' },
  { emoji: '🛑', keywords: 'stop' },
  { emoji: '🚧', keywords: 'construction' },
  { emoji: '⚓', keywords: 'anchor' },
  { emoji: '🛟', keywords: 'ring buoy' },
  { emoji: '⛵', keywords: 'sailboat' },
  { emoji: '🛶', keywords: 'canoe' },
  { emoji: '🚤', keywords: 'speedboat' },
  { emoji: '🛳️', keywords: 'passenger ship' },
  { emoji: '⛴️', keywords: 'ferry' },
  { emoji: '🛥️', keywords: 'motor boat' },
  { emoji: '🚢', keywords: 'ship' },
  { emoji: '✈️', keywords: 'airplane' },
  { emoji: '🛩️', keywords: 'small airplane' },
  { emoji: '🛫', keywords: 'departure' },
  { emoji: '🛬', keywords: 'arrival' },
  { emoji: '🪂', keywords: 'parachute' },
  { emoji: '💺', keywords: 'seat' },
  { emoji: '🚁', keywords: 'helicopter' },
  { emoji: '🚟', keywords: 'suspension railway' },
  { emoji: '🚠', keywords: 'mountain cableway' },
  { emoji: '🚡', keywords: 'aerial tramway' },
  { emoji: '🛰️', keywords: 'satellite' },
  { emoji: '🚀', keywords: 'rocket' },
  { emoji: '🛸', keywords: 'flying saucer' },
  { emoji: '🛎️', keywords: 'bellhop' },
  { emoji: '🧳', keywords: 'luggage' },
  { emoji: '⌛', keywords: 'hourglass' },
  { emoji: '⏳', keywords: 'hourglass flowing' },
  { emoji: '⌚', keywords: 'watch' },
  { emoji: '⏰', keywords: 'alarm' },
  { emoji: '⏱️', keywords: 'stopwatch' },
  { emoji: '⏲️', keywords: 'timer' },
  { emoji: '🕰️', keywords: 'mantelpiece' },
  { emoji: '🕛', keywords: 'twelve' },
  { emoji: '🕐', keywords: 'one' },
  { emoji: '🕑', keywords: 'two' },
  { emoji: '🕒', keywords: 'three' },
  { emoji: '🕓', keywords: 'four' },
  { emoji: '🕔', keywords: 'five' },
  { emoji: '🕕', keywords: 'six' },
  { emoji: '🕖', keywords: 'seven' },
  { emoji: '🕗', keywords: 'eight' },
  { emoji: '🕘', keywords: 'nine' },
  { emoji: '🕙', keywords: 'ten' },
  { emoji: '🕚', keywords: 'eleven' },
  { emoji: '🌑', keywords: 'new moon' },
  { emoji: '🌒', keywords: 'waxing crescent' },
  { emoji: '🌓', keywords: 'first quarter' },
  { emoji: '🌔', keywords: 'waxing gibbous' },
  { emoji: '🌕', keywords: 'full moon' },
  { emoji: '🌖', keywords: 'waning gibbous' },
  { emoji: '🌗', keywords: 'last quarter' },
  { emoji: '🌘', keywords: 'waning crescent' },
  { emoji: '🌙', keywords: 'crescent' },
  { emoji: '🌚', keywords: 'moon лицо луна' },
  { emoji: '🌛', keywords: 'first quarter face' },
  { emoji: '🌜', keywords: 'last quarter face' },
  { emoji: '🌡️', keywords: 'thermometer' },
  { emoji: '☀️', keywords: 'sun' },
  { emoji: '🌝', keywords: 'full moon face' },
  { emoji: '🌞', keywords: 'sun face' },
  { emoji: '🪐', keywords: 'ringed planet' },
  { emoji: '⭐', keywords: 'star' },
  { emoji: '🌟', keywords: 'glowing star' },
  { emoji: '🌠', keywords: 'shooting star' },
  { emoji: '🌌', keywords: 'milky way' },
  { emoji: '☁️', keywords: 'cloud' },
  { emoji: '⛅', keywords: 'sun behind cloud' },
  { emoji: '⛈️', keywords: 'cloud lightning rain' },
  { emoji: '🌤️', keywords: 'sun small cloud' },
  { emoji: '🌥️', keywords: 'sun behind large cloud' },
  { emoji: '🌦️', keywords: 'sun behind rain' },
  { emoji: '🌧️', keywords: 'cloud rain' },
  { emoji: '🌨️', keywords: 'cloud snow' },
  { emoji: '🌩️', keywords: 'cloud lightning' },
  { emoji: '🌪️', keywords: 'tornado' },
  { emoji: '🌫️', keywords: 'fog' },
  { emoji: '🌬️', keywords: 'wind face' },
  { emoji: '🌀', keywords: 'cyclone' },
  { emoji: '🌈', keywords: 'rainbow' },
  { emoji: '🌂', keywords: 'closed umbrella' },
  { emoji: '☂️', keywords: 'umbrella' },
  { emoji: '☔', keywords: 'umbrella rain' },
  { emoji: '⛱️', keywords: 'umbrella ground' },
  { emoji: '⚡', keywords: 'zap lightning молния' },
  { emoji: '❄️', keywords: 'snowflake' },
  { emoji: '☃️', keywords: 'snowman снеговик' },
  { emoji: '⛄', keywords: 'snowman without snow' },
  { emoji: '☄️', keywords: 'comet' },
  { emoji: '🔥', keywords: 'fire огонь огнь круто' },
  { emoji: '💧', keywords: 'droplet' },
  { emoji: '🌊', keywords: 'ocean' },
  { emoji: '🎃', keywords: 'pumpkin halloween тыква' },
  { emoji: '🎄', keywords: 'tree christmas елка' },
  { emoji: '🎆', keywords: 'fireworks' },
  { emoji: '🎇', keywords: 'sparkler' },
  { emoji: '🧨', keywords: 'firecracker' },
  { emoji: '✨', keywords: 'sparkles блеск' },
  { emoji: '🎈', keywords: 'balloon' },
  { emoji: '🎉', keywords: 'party confetti праздник ура' },
  { emoji: '🎊', keywords: 'confetti ball' },
  { emoji: '🎋', keywords: 'tanabata' },
  { emoji: '🎍', keywords: 'pine decoration' },
  { emoji: '🎎', keywords: 'dolls' },
  { emoji: '🎏', keywords: 'carp streamer' },
  { emoji: '🎐', keywords: 'wind chime' },
  { emoji: '🎑', keywords: 'moon ceremony' },
  { emoji: '🧧', keywords: 'red envelope' },
  { emoji: '🎀', keywords: 'ribbon' },
  { emoji: '🎁', keywords: 'gift' },
  { emoji: '🎗️', keywords: 'reminder ribbon' },
  { emoji: '🎟️', keywords: 'tickets' },
  { emoji: '🎫', keywords: 'ticket' },
  { emoji: '🎖️', keywords: 'military medal' },
  { emoji: '🏆', keywords: 'trophy кубок победа' },
  { emoji: '🏅', keywords: 'sports medal' },
  { emoji: '🥇', keywords: 'gold' },
  { emoji: '🥈', keywords: 'silver' },
  { emoji: '🥉', keywords: 'bronze' },
  { emoji: '⚽', keywords: 'soccer' },
  { emoji: '⚾', keywords: 'baseball' },
  { emoji: '🥎', keywords: 'softball' },
  { emoji: '🏀', keywords: 'basketball' },
  { emoji: '🏐', keywords: 'volleyball' },
  { emoji: '🏈', keywords: 'football' },
  { emoji: '🏉', keywords: 'rugby' },
  { emoji: '🎾', keywords: 'tennis' },
  { emoji: '🥏', keywords: 'flying disc' },
  { emoji: '🎳', keywords: 'bowling' },
  { emoji: '🏏', keywords: 'cricket' },
  { emoji: '🏑', keywords: 'field hockey' },
  { emoji: '🏒', keywords: 'ice hockey' },
  { emoji: '🥍', keywords: 'lacrosse' },
  { emoji: '🏓', keywords: 'ping pong' },
  { emoji: '🏸', keywords: 'badminton' },
  { emoji: '🥊', keywords: 'boxing' },
  { emoji: '🥋', keywords: 'martial arts' },
  { emoji: '🥅', keywords: 'goal' },
  { emoji: '⛳', keywords: 'golf' },
  { emoji: '⛸️', keywords: 'ice skate' },
  { emoji: '🎣', keywords: 'fishing' },
  { emoji: '🤿', keywords: 'diving mask' },
  { emoji: '🎽', keywords: 'running shirt' },
  { emoji: '🎿', keywords: 'skis' },
  { emoji: '🛷', keywords: 'sled' },
  { emoji: '🥌', keywords: 'curling' },
  { emoji: '🎯', keywords: 'direct hit' },
  { emoji: '🪀', keywords: 'yo-yo' },
  { emoji: '🪁', keywords: 'kite' },
  { emoji: '🎱', keywords: '8ball' },
  { emoji: '🔮', keywords: 'crystal ball' },
  { emoji: '🪄', keywords: 'magic wand' },
  { emoji: '🧿', keywords: 'nazar' },
  { emoji: '🪬', keywords: 'hamsa' },
  { emoji: '🎮', keywords: 'video game' },
  { emoji: '🕹️', keywords: 'joystick' },
  { emoji: '🎰', keywords: 'slot' },
  { emoji: '🎲', keywords: 'dice' },
  { emoji: '🧩', keywords: 'puzzle' },
  { emoji: '🧸', keywords: 'teddy' },
  { emoji: '🪅', keywords: 'pinata' },
  { emoji: '🪩', keywords: 'mirror ball' },
  { emoji: '🪆', keywords: 'nesting dolls' },
  { emoji: '♠️', keywords: 'spades' },
  { emoji: '♥️', keywords: 'hearts' },
  { emoji: '♦️', keywords: 'diamonds' },
  { emoji: '♣️', keywords: 'clubs' },
  { emoji: '♟️', keywords: 'chess' },
  { emoji: '🃏', keywords: 'joker' },
  { emoji: '🀄', keywords: 'mahjong' },
  { emoji: '🎴', keywords: 'flower cards' },
  { emoji: '🎭', keywords: 'performing arts' },
  { emoji: '🖼️', keywords: 'framed picture' },
  { emoji: '🎨', keywords: 'art' },
  { emoji: '🧵', keywords: 'thread' },
  { emoji: '🪡', keywords: 'needle' },
  { emoji: '🧶', keywords: 'yarn' },
  { emoji: '🪢', keywords: 'knot' },
  { emoji: '👓', keywords: 'glasses' },
  { emoji: '🕶️', keywords: 'sunglasses' },
  { emoji: '🥽', keywords: 'goggles' },
  { emoji: '🥼', keywords: 'lab coat' },
  { emoji: '🦺', keywords: 'safety vest' },
  { emoji: '👔', keywords: 'necktie' },
  { emoji: '👕', keywords: 'tshirt' },
  { emoji: '👖', keywords: 'jeans' },
  { emoji: '🧣', keywords: 'scarf' },
  { emoji: '🧤', keywords: 'gloves' },
  { emoji: '🧥', keywords: 'coat' },
  { emoji: '🧦', keywords: 'socks' },
  { emoji: '👗', keywords: 'dress' },
  { emoji: '👘', keywords: 'kimono' },
  { emoji: '🥻', keywords: 'sari' },
  { emoji: '🩱', keywords: 'one piece' },
  { emoji: '🩲', keywords: 'briefs' },
  { emoji: '🩳', keywords: 'shorts' },
  { emoji: '👙', keywords: 'bikini' },
  { emoji: '👚', keywords: 'blouse' },
  { emoji: '👛', keywords: 'purse' },
  { emoji: '👜', keywords: 'handbag' },
  { emoji: '👝', keywords: 'clutch' },
  { emoji: '🛍️', keywords: 'shopping bags' },
  { emoji: '🎒', keywords: 'backpack' },
  { emoji: '🩴', keywords: 'thong sandal' },
  { emoji: '👞', keywords: 'mans shoe' },
  { emoji: '👟', keywords: 'sneaker' },
  { emoji: '🥾', keywords: 'hiking boot' },
  { emoji: '🥿', keywords: 'flat shoe' },
  { emoji: '👠', keywords: 'high heel' },
  { emoji: '👡', keywords: 'sandal' },
  { emoji: '🩰', keywords: 'ballet' },
  { emoji: '👢', keywords: 'boot' },
  { emoji: '👑', keywords: 'crown' },
  { emoji: '👒', keywords: 'womans hat' },
  { emoji: '🎩', keywords: 'top hat' },
  { emoji: '🎓', keywords: 'graduation' },
  { emoji: '🧢', keywords: 'billed cap' },
  { emoji: '🪖', keywords: 'military helmet' },
  { emoji: '⛑️', keywords: 'rescue helmet' },
  { emoji: '📿', keywords: 'prayer beads' },
  { emoji: '💄', keywords: 'lipstick' },
  { emoji: '💍', keywords: 'ring' },
  { emoji: '💎', keywords: 'gem' },
  { emoji: '🔇', keywords: 'muted' },
  { emoji: '🔈', keywords: 'speaker low' },
  { emoji: '🔉', keywords: 'speaker med' },
  { emoji: '🔊', keywords: 'speaker high' },
  { emoji: '📢', keywords: 'loudspeaker' },
  { emoji: '📣', keywords: 'megaphone' },
  { emoji: '📯', keywords: 'postal horn' },
  { emoji: '🔔', keywords: 'bell' },
  { emoji: '🔕', keywords: 'bell slash' },
  { emoji: '🎼', keywords: 'score' },
  { emoji: '🎵', keywords: 'note' },
  { emoji: '🎶', keywords: 'notes' },
  { emoji: '🎙️', keywords: 'studio mic' },
  { emoji: '🎚️', keywords: 'level slider' },
  { emoji: '🎛️', keywords: 'control knobs' },
  { emoji: '🎤', keywords: 'microphone' },
  { emoji: '🎧', keywords: 'headphone' },
  { emoji: '📻', keywords: 'radio' },
  { emoji: '🎷', keywords: 'saxophone' },
  { emoji: '🪗', keywords: 'accordion' },
  { emoji: '🎸', keywords: 'guitar' },
  { emoji: '🎹', keywords: 'piano' },
  { emoji: '🎺', keywords: 'trumpet' },
  { emoji: '🎻', keywords: 'violin' },
  { emoji: '🪕', keywords: 'banjo' },
  { emoji: '🥁', keywords: 'drum' },
  { emoji: '🪘', keywords: 'long drum' },
  { emoji: '📱', keywords: 'phone' },
  { emoji: '📲', keywords: 'phone arrow' },
  { emoji: '☎️', keywords: 'telephone' },
  { emoji: '📞', keywords: 'receiver' },
  { emoji: '📟', keywords: 'pager' },
  { emoji: '📠', keywords: 'fax' },
  { emoji: '🔋', keywords: 'battery' },
  { emoji: '🪫', keywords: 'low battery' },
  { emoji: '🔌', keywords: 'plug' },
  { emoji: '💻', keywords: 'laptop' },
  { emoji: '🖥️', keywords: 'desktop' },
  { emoji: '🖨️', keywords: 'printer' },
  { emoji: '⌨️', keywords: 'keyboard' },
  { emoji: '🖱️', keywords: 'mouse' },
  { emoji: '🖲️', keywords: 'trackball' },
  { emoji: '💽', keywords: 'minidisc' },
  { emoji: '💾', keywords: 'floppy' },
  { emoji: '💿', keywords: 'cd' },
  { emoji: '📀', keywords: 'dvd' },
  { emoji: '🧮', keywords: 'abacus' },
  { emoji: '🎥', keywords: 'movie camera' },
  { emoji: '🎞️', keywords: 'film frames' },
  { emoji: '📽️', keywords: 'projector' },
  { emoji: '🎬', keywords: 'clapper' },
  { emoji: '📺', keywords: 'tv' },
  { emoji: '📷', keywords: 'camera' },
  { emoji: '📸', keywords: 'camera flash' },
  { emoji: '📹', keywords: 'video camera' },
  { emoji: '📼', keywords: 'vhs' },
  { emoji: '🔍', keywords: 'mag right' },
  { emoji: '🔎', keywords: 'mag left' },
  { emoji: '🕯️', keywords: 'candle' },
  { emoji: '💡', keywords: 'bulb' },
  { emoji: '🔦', keywords: 'flashlight' },
  { emoji: '🏮', keywords: 'red lantern' },
  { emoji: '🪔', keywords: 'diya' },
  { emoji: '📔', keywords: 'notebook decorative' },
  { emoji: '📕', keywords: 'closed book' },
  { emoji: '📖', keywords: 'open book' },
  { emoji: '📗', keywords: 'green book' },
  { emoji: '📘', keywords: 'blue book' },
  { emoji: '📙', keywords: 'orange book' },
  { emoji: '📚', keywords: 'books' },
  { emoji: '📓', keywords: 'notebook' },
  { emoji: '📒', keywords: 'ledger' },
  { emoji: '📃', keywords: 'page curl' },
  { emoji: '📜', keywords: 'scroll' },
  { emoji: '📄', keywords: 'page' },
  { emoji: '📰', keywords: 'newspaper' },
  { emoji: '🗞️', keywords: 'rolled newspaper' },
  { emoji: '📑', keywords: 'bookmark tabs' },
  { emoji: '🔖', keywords: 'bookmark' },
  { emoji: '🏷️', keywords: 'label' },
  { emoji: '💰', keywords: 'money bag' },
  { emoji: '🪙', keywords: 'coin' },
  { emoji: '💴', keywords: 'yen' },
  { emoji: '💵', keywords: 'dollar' },
  { emoji: '💶', keywords: 'euro' },
  { emoji: '💷', keywords: 'pound' },
  { emoji: '💸', keywords: 'money wings' },
  { emoji: '💳', keywords: 'credit card' },
  { emoji: '🧾', keywords: 'receipt' },
  { emoji: '💹', keywords: 'chart' },
  { emoji: '✉️', keywords: 'envelope' },
  { emoji: '📧', keywords: 'email' },
  { emoji: '📨', keywords: 'incoming' },
  { emoji: '📩', keywords: 'envelope arrow' },
  { emoji: '📤', keywords: 'outbox' },
  { emoji: '📥', keywords: 'inbox' },
  { emoji: '📦', keywords: 'package' },
  { emoji: '📫', keywords: 'mailbox' },
  { emoji: '📪', keywords: 'mailbox closed' },
  { emoji: '📬', keywords: 'mailbox with mail' },
  { emoji: '📭', keywords: 'mailbox no mail' },
  { emoji: '📮', keywords: 'postbox' },
  { emoji: '🗳️', keywords: 'ballot' },
  { emoji: '✏️', keywords: 'pencil' },
  { emoji: '✒️', keywords: 'black nib' },
  { emoji: '🖋️', keywords: 'fountain pen' },
  { emoji: '🖊️', keywords: 'pen' },
  { emoji: '🖌️', keywords: 'paintbrush' },
  { emoji: '🖍️', keywords: 'crayon' },
  { emoji: '📝', keywords: 'memo' },
  { emoji: '💼', keywords: 'briefcase' },
  { emoji: '📁', keywords: 'folder' },
  { emoji: '📂', keywords: 'open folder' },
  { emoji: '🗂️', keywords: 'card index' },
  { emoji: '📅', keywords: 'calendar' },
  { emoji: '📆', keywords: 'tear calendar' },
  { emoji: '🗒️', keywords: 'spiral notepad' },
  { emoji: '🗓️', keywords: 'spiral calendar' },
  { emoji: '📇', keywords: 'card index' },
  { emoji: '📈', keywords: 'chart up' },
  { emoji: '📉', keywords: 'chart down' },
  { emoji: '📊', keywords: 'bar chart' },
  { emoji: '📋', keywords: 'clipboard' },
  { emoji: '📌', keywords: 'pushpin' },
  { emoji: '📍', keywords: 'round pushpin' },
  { emoji: '📎', keywords: 'paperclip' },
  { emoji: '🖇️', keywords: 'linked paperclips' },
  { emoji: '📏', keywords: 'ruler' },
  { emoji: '📐', keywords: 'triangle ruler' },
  { emoji: '✂️', keywords: 'scissors' },
  { emoji: '🗃️', keywords: 'card file box' },
  { emoji: '🗄️', keywords: 'file cabinet' },
  { emoji: '🗑️', keywords: 'wastebasket' },
  { emoji: '🔒', keywords: 'lock' },
  { emoji: '🔓', keywords: 'unlock' },
  { emoji: '🔏', keywords: 'lock pen' },
  { emoji: '🔐', keywords: 'lock key' },
  { emoji: '🔑', keywords: 'key' },
  { emoji: '🗝️', keywords: 'old key' },
  { emoji: '🔨', keywords: 'hammer' },
  { emoji: '🪓', keywords: 'axe' },
  { emoji: '⛏️', keywords: 'pick' },
  { emoji: '⚒️', keywords: 'hammer pick' },
  { emoji: '🛠️', keywords: 'hammer wrench' },
  { emoji: '🗡️', keywords: 'dagger' },
  { emoji: '⚔️', keywords: 'crossed swords' },
  { emoji: '🔫', keywords: 'pistol' },
  { emoji: '🪃', keywords: 'boomerang' },
  { emoji: '🏹', keywords: 'bow arrow' },
  { emoji: '🛡️', keywords: 'shield' },
  { emoji: '🪚', keywords: 'saw' },
  { emoji: '🔧', keywords: 'wrench' },
  { emoji: '🪛', keywords: 'screwdriver' },
  { emoji: '🔩', keywords: 'nut bolt' },
  { emoji: '⚙️', keywords: 'gear' },
  { emoji: '🗜️', keywords: 'clamp' },
  { emoji: '⚖️', keywords: 'balance' },
  { emoji: '🦯', keywords: 'white cane' },
  { emoji: '🔗', keywords: 'link' },
  { emoji: '⛓️', keywords: 'chains' },
  { emoji: '🪝', keywords: 'hook' },
  { emoji: '🧰', keywords: 'toolbox' },
  { emoji: '🧲', keywords: 'magnet' },
  { emoji: '🪜', keywords: 'ladder' },
  { emoji: '⚗️', keywords: 'alembic' },
  { emoji: '🧪', keywords: 'test tube' },
  { emoji: '🧫', keywords: 'petri' },
  { emoji: '🧬', keywords: 'dna' },
  { emoji: '🔬', keywords: 'microscope' },
  { emoji: '🔭', keywords: 'telescope' },
  { emoji: '📡', keywords: 'satellite antenna' },
  { emoji: '💉', keywords: 'syringe' },
  { emoji: '🩸', keywords: 'drop blood' },
  { emoji: '💊', keywords: 'pill таблетка' },
  { emoji: '🩹', keywords: 'adhesive bandage' },
  { emoji: '🩺', keywords: 'stethoscope' },
  { emoji: '🩻', keywords: 'xray' },
  { emoji: '🚪', keywords: 'door' },
  { emoji: '🛗', keywords: 'elevator' },
  { emoji: '🪞', keywords: 'mirror' },
  { emoji: '🪟', keywords: 'window' },
  { emoji: '🛏️', keywords: 'bed' },
  { emoji: '🛋️', keywords: 'couch' },
  { emoji: '🪑', keywords: 'chair' },
  { emoji: '🚽', keywords: 'toilet' },
  { emoji: '🪠', keywords: 'plunger' },
  { emoji: '🚿', keywords: 'shower' },
  { emoji: '🛁', keywords: 'bathtub' },
  { emoji: '🪤', keywords: 'mouse trap' },
  { emoji: '🪒', keywords: 'razor' },
  { emoji: '🧴', keywords: 'lotion' },
  { emoji: '🧷', keywords: 'safety pin' },
  { emoji: '🧹', keywords: 'broom' },
  { emoji: '🧺', keywords: 'basket' },
  { emoji: '🧻', keywords: 'roll paper' },
  { emoji: '🪣', keywords: 'bucket' },
  { emoji: '🧼', keywords: 'soap' },
  { emoji: '🪥', keywords: 'toothbrush' },
  { emoji: '🧽', keywords: 'sponge' },
  { emoji: '🧯', keywords: 'fire extinguisher' },
  { emoji: '🛒', keywords: 'cart' },
  { emoji: '🚬', keywords: 'cigarette' },
  { emoji: '⚰️', keywords: 'coffin' },
  { emoji: '🪦', keywords: 'headstone' },
  { emoji: '⚱️', keywords: 'urn' },
  { emoji: '🗿', keywords: 'moai статуя' },
  { emoji: '🪧', keywords: 'placard' },
  { emoji: '🪪', keywords: 'id card' },
  { emoji: '🏧', keywords: 'atm' },
  { emoji: '🚮', keywords: 'litter' },
  { emoji: '🚰', keywords: 'potable' },
  { emoji: '♿', keywords: 'wheelchair' },
  { emoji: '🚹', keywords: 'mens' },
  { emoji: '🚺', keywords: 'womens' },
  { emoji: '🚻', keywords: 'restroom' },
  { emoji: '🚼', keywords: 'baby symbol' },
  { emoji: '🚾', keywords: 'wc' },
  { emoji: '🛂', keywords: 'passport' },
  { emoji: '🛃', keywords: 'customs' },
  { emoji: '🛄', keywords: 'baggage' },
  { emoji: '🛅', keywords: 'left luggage' },
  { emoji: '⚠️', keywords: 'warning' },
  { emoji: '🚸', keywords: 'children crossing' },
  { emoji: '⛔', keywords: 'no entry' },
  { emoji: '🚫', keywords: 'prohibited' },
  { emoji: '🚳', keywords: 'no bicycles' },
  { emoji: '🚭', keywords: 'no smoking' },
  { emoji: '🚯', keywords: 'no littering' },
  { emoji: '🚱', keywords: 'non potable' },
  { emoji: '🚷', keywords: 'no pedestrians' },
  { emoji: '📵', keywords: 'no mobile' },
  { emoji: '🔞', keywords: 'underage' },
  { emoji: '☢️', keywords: 'radioactive' },
  { emoji: '☣️', keywords: 'biohazard' },
  { emoji: '⬆️', keywords: 'up' },
  { emoji: '↗️', keywords: 'up right' },
  { emoji: '➡️', keywords: 'right' },
  { emoji: '↘️', keywords: 'down right' },
  { emoji: '⬇️', keywords: 'down' },
  { emoji: '↙️', keywords: 'down left' },
  { emoji: '⬅️', keywords: 'left' },
  { emoji: '↖️', keywords: 'up left' },
  { emoji: '↕️', keywords: 'up down' },
  { emoji: '↔️', keywords: 'left right' },
  { emoji: '↩️', keywords: 'right arrow curving left' },
  { emoji: '↪️', keywords: 'left arrow curving right' },
  { emoji: '⤴️', keywords: 'right arrow curving up' },
  { emoji: '⤵️', keywords: 'right arrow curving down' },
  { emoji: '🔃', keywords: 'clockwise' },
  { emoji: '🔄', keywords: 'counterclockwise' },
  { emoji: '🔙', keywords: 'back' },
  { emoji: '🔚', keywords: 'end' },
  { emoji: '🔛', keywords: 'on' },
  { emoji: '🔜', keywords: 'soon' },
  { emoji: '🔝', keywords: 'top' },
  { emoji: '🛐', keywords: 'place of worship' },
  { emoji: '⚛️', keywords: 'atom' },
  { emoji: '🕉️', keywords: 'om' },
  { emoji: '✡️', keywords: 'star of david' },
  { emoji: '☸️', keywords: 'wheel of dharma' },
  { emoji: '☯️', keywords: 'yin yang' },
  { emoji: '✝️', keywords: 'latin cross' },
  { emoji: '☦️', keywords: 'orthodox cross' },
  { emoji: '☪️', keywords: 'star crescent' },
  { emoji: '☮️', keywords: 'peace' },
  { emoji: '🕎', keywords: 'menorah' },
  { emoji: '🔯', keywords: 'dotted six' },
  { emoji: '♈', keywords: 'aries' },
  { emoji: '♉', keywords: 'taurus' },
  { emoji: '♊', keywords: 'gemini' },
  { emoji: '♋', keywords: 'cancer' },
  { emoji: '♌', keywords: 'leo' },
  { emoji: '♍', keywords: 'virgo' },
  { emoji: '♎', keywords: 'libra' },
  { emoji: '♏', keywords: 'scorpio' },
  { emoji: '♐', keywords: 'sagittarius' },
  { emoji: '♑', keywords: 'capricorn' },
  { emoji: '♒', keywords: 'aquarius' },
  { emoji: '♓', keywords: 'pisces' },
  { emoji: '⛎', keywords: 'ophiuchus' },
  { emoji: '🔀', keywords: 'shuffle' },
  { emoji: '🔁', keywords: 'repeat' },
  { emoji: '🔂', keywords: 'repeat one' },
  { emoji: '▶️', keywords: 'play' },
  { emoji: '⏩', keywords: 'fast forward' },
  { emoji: '⏭️', keywords: 'next track' },
  { emoji: '⏯️', keywords: 'play pause' },
  { emoji: '◀️', keywords: 'reverse' },
  { emoji: '⏪', keywords: 'fast reverse' },
  { emoji: '⏮️', keywords: 'last track' },
  { emoji: '🔼', keywords: 'up button' },
  { emoji: '⏫', keywords: 'fast up' },
  { emoji: '🔽', keywords: 'down button' },
  { emoji: '⏬', keywords: 'fast down' },
  { emoji: '⏸️', keywords: 'pause' },
  { emoji: '⏹️', keywords: 'stop' },
  { emoji: '⏺️', keywords: 'record' },
  { emoji: '⏏️', keywords: 'eject' },
  { emoji: '🎦', keywords: 'cinema' },
  { emoji: '🔅', keywords: 'dim' },
  { emoji: '🔆', keywords: 'bright' },
  { emoji: '📶', keywords: 'signal' },
  { emoji: '📳', keywords: 'vibration' },
  { emoji: '📴', keywords: 'phone off' },
  { emoji: '♀️', keywords: 'female' },
  { emoji: '♂️', keywords: 'male' },
  { emoji: '⚧️', keywords: 'transgender' },
  { emoji: '✖️', keywords: 'multiply' },
  { emoji: '➕', keywords: 'plus' },
  { emoji: '➖', keywords: 'minus' },
  { emoji: '➗', keywords: 'divide' },
  { emoji: '♾️', keywords: 'infinity' },
  { emoji: '‼️', keywords: 'double exclamation' },
  { emoji: '⁉️', keywords: 'exclamation question' },
  { emoji: '❓', keywords: 'question' },
  { emoji: '❔', keywords: 'white question' },
  { emoji: '❕', keywords: 'white exclamation' },
  { emoji: '❗', keywords: 'exclamation' },
  { emoji: '〰️', keywords: 'wavy dash' },
  { emoji: '💱', keywords: 'currency' },
  { emoji: '💲', keywords: 'dollar sign' },
  { emoji: '⚕️', keywords: 'medical' },
  { emoji: '♻️', keywords: 'recycle' },
  { emoji: '⚜️', keywords: 'fleur' },
  { emoji: '🔱', keywords: 'trident' },
  { emoji: '📛', keywords: 'name badge' },
  { emoji: '🔰', keywords: 'japanese beginner' },
  { emoji: '⭕', keywords: 'hollow red' },
  { emoji: '✅', keywords: 'check mark button' },
  { emoji: '☑️', keywords: 'check box' },
  { emoji: '✔️', keywords: 'check mark' },
  { emoji: '❌', keywords: 'cross mark' },
  { emoji: '❎', keywords: 'cross mark button' },
  { emoji: '➰', keywords: 'curly loop' },
  { emoji: '➿', keywords: 'double curly' },
  { emoji: '〽️', keywords: 'part alternation' },
  { emoji: '✳️', keywords: 'eight spoked' },
  { emoji: '✴️', keywords: 'eight pointed' },
  { emoji: '❇️', keywords: 'sparkle' },
  { emoji: '©️', keywords: 'copyright' },
  { emoji: '®️', keywords: 'registered' },
  { emoji: '™️', keywords: 'tm' },
  { emoji: '🔟', keywords: 'keycap 10' },
  { emoji: '🔠', keywords: 'input latin upper' },
  { emoji: '🔡', keywords: 'input latin lower' },
  { emoji: '🔢', keywords: 'input numbers' },
  { emoji: '🔣', keywords: 'input symbols' },
  { emoji: '🔤', keywords: 'input latin' },
  { emoji: '🅰️', keywords: 'a button' },
  { emoji: '🆎', keywords: 'ab button' },
  { emoji: '🅱️', keywords: 'b button' },
  { emoji: '🆑', keywords: 'cl' },
  { emoji: '🆒', keywords: 'cool круто' },
  { emoji: '🆓', keywords: 'free' },
  { emoji: 'ℹ️', keywords: 'info' },
  { emoji: '🆔', keywords: 'id' },
  { emoji: 'Ⓜ️', keywords: 'circled m' },
  { emoji: '🆕', keywords: 'new' },
  { emoji: '🆖', keywords: 'ng' },
  { emoji: '🅾️', keywords: 'o button' },
  { emoji: '🆗', keywords: 'ok button' },
  { emoji: '🅿️', keywords: 'p button' },
  { emoji: '🆘', keywords: 'sos' },
  { emoji: '🆙', keywords: 'up!' },
  { emoji: '🆚', keywords: 'vs' },
  { emoji: '🈁', keywords: 'here' },
  { emoji: '🈂️', keywords: 'service' },
  { emoji: '🈷️', keywords: 'monthly' },
  { emoji: '🈶', keywords: 'not free' },
  { emoji: '🈯', keywords: 'reserved' },
  { emoji: '🉐', keywords: 'bargain' },
  { emoji: '🈹', keywords: 'discount' },
  { emoji: '🈚', keywords: 'free of charge' },
  { emoji: '🈲', keywords: 'prohibited' },
  { emoji: '🉑', keywords: 'acceptable' },
  { emoji: '🈸', keywords: 'application' },
  { emoji: '🈴', keywords: 'passing' },
  { emoji: '🈳', keywords: 'vacancy' },
  { emoji: '㊗️', keywords: 'congratulations' },
  { emoji: '㊙️', keywords: 'secret' },
  { emoji: '🈺', keywords: 'open' },
  { emoji: '🈵', keywords: 'no vacancy' },
  { emoji: '🔴', keywords: 'red circle' },
  { emoji: '🟠', keywords: 'orange circle' },
  { emoji: '🟡', keywords: 'yellow circle' },
  { emoji: '🟢', keywords: 'green circle' },
  { emoji: '🔵', keywords: 'blue circle' },
  { emoji: '🟣', keywords: 'purple circle' },
  { emoji: '🟤', keywords: 'brown circle' },
  { emoji: '⚫', keywords: 'black circle' },
  { emoji: '⚪', keywords: 'white circle' },
  { emoji: '🟥', keywords: 'red square' },
  { emoji: '🟧', keywords: 'orange square' },
  { emoji: '🟨', keywords: 'yellow square' },
  { emoji: '🟩', keywords: 'green square' },
  { emoji: '🟦', keywords: 'blue square' },
  { emoji: '🟪', keywords: 'purple square' },
  { emoji: '🟫', keywords: 'brown square' },
  { emoji: '⬛', keywords: 'black large' },
  { emoji: '⬜', keywords: 'white large' },
  { emoji: '◼️', keywords: 'black medium' },
  { emoji: '◻️', keywords: 'white medium' },
  { emoji: '◾', keywords: 'black medium small' },
  { emoji: '◽', keywords: 'white medium small' },
  { emoji: '▪️', keywords: 'black small' },
  { emoji: '▫️', keywords: 'white small' },
  { emoji: '🔶', keywords: 'large orange diamond' },
  { emoji: '🔷', keywords: 'large blue diamond' },
  { emoji: '🔸', keywords: 'small orange diamond' },
  { emoji: '🔹', keywords: 'small blue diamond' },
  { emoji: '🔺', keywords: 'red triangle up' },
  { emoji: '🔻', keywords: 'red triangle down' },
  { emoji: '💠', keywords: 'diamond with dot' },
  { emoji: '🔘', keywords: 'radio button' },
  { emoji: '🔳', keywords: 'white square button' },
  { emoji: '🔲', keywords: 'black square button' },
  { emoji: '🏁', keywords: 'chequered flag' },
  { emoji: '🚩', keywords: 'triangular flag' },
  { emoji: '🎌', keywords: 'crossed flags' },
  { emoji: '🏴', keywords: 'black flag' },
  { emoji: '🏳️', keywords: 'white flag' },
  { emoji: '🏳️‍⚧️', keywords: 'transgender flag' },
  { emoji: '🏴‍☠️', keywords: 'pirate flag' },
  { emoji: '🫡', keywords: 'salute салют' },
  { emoji: '🫠', keywords: 'melting' },
  { emoji: '🫢', keywords: 'hand over mouth open eyes' },
  { emoji: '🫣', keywords: 'peeking' },
  { emoji: '🫤', keywords: 'diagonal mouth' },
  { emoji: '🫨', keywords: 'shaking face' },
]
