#!/usr/bin/env bash
# Build src/shared/ui/twemojiCodes.generated.ts from public/twemoji/72x72 PNGs.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/public/twemoji/72x72"
OUT="$ROOT/src/shared/ui/twemojiCodes.generated.ts"

if [[ ! -d "$DIR" ]]; then
  echo "Missing $DIR — run bash scripts/fetch-twemoji.sh first" >&2
  exit 1
fi

python3 - "$DIR" "$OUT" <<'PY'
import sys
from pathlib import Path

dir_path = Path(sys.argv[1])
out = Path(sys.argv[2])
codes = sorted(p.stem.lower() for p in dir_path.glob("*.png"))
lines = [
    "// AUTO-GENERATED by scripts/generate-twemoji-index.sh — do not edit.",
    f"// {len(codes)} Twemoji PNG basenames from public/twemoji/72x72",
    "const codes: Record<string, 1> = {",
]
for c in codes:
    lines.append(f"  '{c}': 1,")
lines += [
    "}",
    "",
    "export function twemojiCodeExists(code: string): boolean {",
    "  return codes[code.toLowerCase()] === 1",
    "}",
    "",
    "export function twemojiKnownCodeCount(): number {",
    f"  return {len(codes)}",
    "}",
    "",
]
out.write_text("\n".join(lines))
print(f"Wrote {out.relative_to(Path.cwd()) if out.is_relative_to(Path.cwd()) else out} ({len(codes)} codes)")
PY
